var GridConstants = {
		VERTICAL_RECORD_SHOW_LIMT : 10,
		HORIZONTAL_COLUMN_SHOW_LIMIT : 8,
		DEFAULT_NUMBER_OF_RECORDS_PER_PAGE : 10,
		HORIZONTAL_MAX_ACTION_BUTTON_LIMIT : 3,
		VERTICAL_COLUMN_SHOW_LIMIT_IN_COLUMN_SHOW_HIDE_COMPONENT : 15,
		VERTICAL_FILTER_OPTION_SHOW_LIMIT_IN_LIST_FILTER_COMPONENT : 15,
}