package com.constants.components;

import com.constants.ApplicationConstants;

public interface EnquiryConstants extends ApplicationConstants {
	
	String MATCH_STATUS_ABANDONED = "ABANDONED";
	String MATCH_STATUS_MAPPED = "MAPPED";
	String MATCH_STATUS_PENDING = "PENDING";
	
	String VALIDATION_MESSAGE_INVALID_CUSTOMER_ID = "Invalid Customer Id.";
	String VALIDATION_MESSAGE_INVALID_ENQUIRY_ID = "Invalid Enquiry Id.";
	String VALIDATION_MESSAGE_INVALID_TUTOR_MAPPER_ID = "Invalid Tutor Mapper Id.";
	String VALIDATION_MESSAGE_INVALID_TUTOR_ID_LIST = "Invalid Tutor Id List.";
	String VALIDATION_MESSAGE_INVALID_TUTOR_MAPPER_ID_LIST = "Invalid Tutor Mapper Id List.";
	String VALIDATION_MESSAGE_INVALID_SCHEDULE_TIME = "Invalid Schedule Date & Time..";
	
	String VELOCITY_TEMPLATES_ENQUIRIES_PATH = AdminConstants.VELOCITY_TEMPLATES_ADMIN_FOLDER_PATH + "/enquiries";
	String VELOCITY_TEMPLATES_DEMO_SCHEDULED_TUTOR_EMAIL_PATH = VELOCITY_TEMPLATES_ENQUIRIES_PATH + "/demo-scheduled-tutor-email.vm";
	String VELOCITY_TEMPLATES_DEMO_SCHEDULED_CLIENT_EMAIL_PATH = VELOCITY_TEMPLATES_ENQUIRIES_PATH + "/demo-scheduled-client-email.vm";
	
	String RESPONSE_MAP_ATTRIBUTE_FAILURE_MESSAGE = "FAILURE_MESSAGE";
	String RESPONSE_MAP_ATTRIBUTE_FAILURE = "FAILURE";
}
