package com.constants.components;

public interface SelectLookupConstants extends CommonsConstants {
	
	String SELECT_LOOKUP_TABLE_PREFERRED_TIME_LOOKUP = "PREFERRED_TIME_LOOKUP";
	String SELECT_LOOKUP_TABLE_LOCATIONS_LOOKUP = "LOCATIONS_LOOKUP";
	String SELECT_LOOKUP_TABLE_SUBJECTS_LOOKUP = "SUBJECTS_LOOKUP";
	String SELECT_LOOKUP_TABLE_TRANSPORT_MODE_LOOKUP = "TRANSPORT_MODE_LOOKUP";
	String SELECT_LOOKUP_TABLE_PROFESSION_LOOKUP = "PROFESSION_LOOKUP";
	String SELECT_LOOKUP_TABLE_QUALIFICATION_LOOKUP = "QUALIFICATION_LOOKUP";
	String SELECT_LOOKUP_TABLE_GENDER_LOOKUP = "GENDER_LOOKUP";
	String SELECT_LOOKUP_TABLE_STUDENT_GRADE_LOOKUP = "STUDENT_GRADE_LOOKUP";
	String SELECT_LOOKUP_TABLE_PREFERRED_TEACHING_TYPE_LOOKUP = "PREFERRED_TEACHING_TYPE_LOOKUP";
	String SELECT_LOOKUP_TABLE_REFERENCE_LOOKUP = "REFERENCE_LOOKUP";
}
