package com.constants.components.publicaccess;

public interface SubmitQueryConstants extends PublicAccessConstants {
	
	String TABLE_NAME = "SUBMIT_QUERY";
	
	String COLUMN_NAME_RECORD_LAST_UPDATED = "RECORD_LAST_UPDATED";
	String COLUMN_NAME_CONTACTED_DATE = "CONTACTED_DATE";
	String COLUMN_NAME_WHO_CONTACTED = "WHO_CONTACTED";
	String COLUMN_NAME_IS_CONTACTED = "IS_CONTACTED";
	String COLUMN_NAME_EMAIL_ID = "EMAIL_ID";
	String COLUMN_NAME_WHO_NOT_ANSWERED = "WHO_NOT_ANSWERED";
	String COLUMN_NAME_NOT_ANSWERED_REASON = "NOT_ANSWERED_REASON";
	String COLUMN_NAME_NOT_ANSWERED = "NOT_ANSWERED";
	String COLUMN_NAME_QUERY_RESPONSE = "QUERY_RESPONSE";
	String COLUMN_NAME_QUERY_DETAILS = "QUERY_DETAILS";
	String COLUMN_NAME_SUBSCRIBED_CUSTOMER = "SUBSCRIBED_CUSTOMER";
	String COLUMN_NAME_REGISTERED_TUTOR = "REGISTERED_TUTOR";
	String COLUMN_NAME_QUERY_STATUS = "QUERY_STATUS";
	String COLUMN_NAME_QUERY_REQUESTED_DATE = "QUERY_REQUESTED_DATE";
	String COLUMN_NAME_QUERY_ID = "QUERY_ID";
	
	String VALIDATION_MESSAGE_PLEASE_ENTER_A_VALID_EMAIL_ID = "Please enter a valid 'Email Id'";
	String VALIDATION_MESSAGE_PLEASE_ENTER_A_VALID_QUERY = "Please provide some 'Query'";
}
